[package]
name = "ymodem-send-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default =[]
async = ["tokio","tokio/io-util", "serial2-tokio"]
[dependencies]
serial2 = "0.2.33"

serial2-tokio = { version = "0.1.19", optional = true }
tokio = { version = "1.48.0", default_features =false, optional=true}
